
// Report Generation Logic using jsPDF
// Expects: jsPDF, autoTable, and active Alpine scope data

async function generatePDF(data) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const width = doc.internal.pageSize.getWidth();
    const height = doc.internal.pageSize.getHeight();
    const margin = 20;

    // --- Helpers ---
    const addHeader = (title) => {
        doc.setFillColor(79, 70, 229); // Indigo 600
        doc.rect(0, 0, width, 20, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text(title, margin, 13);
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
        doc.text(date, width - margin, 13, { align: 'right' });
    };

    const addFooter = (pageNo) => {
        doc.setTextColor(150);
        doc.setFontSize(8);
        doc.text("Generated by UK Property Strategy Simulator", margin, height - 10);
        doc.text(`Page ${pageNo}`, width - margin, height - 10, { align: 'right' });
    };

    const getChartImage = (id) => {
        const canvas = document.getElementById(id);
        return canvas.toDataURL('image/png', 1.0);
    };

    // --- Data Preparation ---
    const r = data.results;
    if (!r) return alert("Please run the simulation first.");
    
    // Determine Winner (Reuse logic from miniResult/headline)
    const idx = data.simYears - 1;
    const strats = [
        {name: 'Rent & Invest', val: data.getNW(r.stratA, idx), type: 'Rent', color: [148, 163, 184]}, // Slate
        {name: 'Buy Home', val: r.possibleB ? data.getNW(r.stratB, idx) : -Infinity, type: 'Buy', color: [37, 99, 235]}, // Blue
        {name: 'Buy + Lodger', val: r.possibleB ? data.getNW(r.stratC, idx) : -Infinity, type: 'Buy', color: [16, 185, 129]}, // Emerald
        {name: 'BTL (Ltd Co)', val: r.possibleD ? data.getNW(r.stratD, idx) : -Infinity, type: 'Buy', color: [139, 92, 246]}, // Violet
        {name: 'BTL (Personal)', val: r.possibleE ? data.getNW(r.stratE, idx) : -Infinity, type: 'Buy', color: [249, 115, 22]}, // Orange
        {name: 'Home + BTL', val: r.possibleF ? data.getNW(r.stratF, idx) : -Infinity, type: 'Buy', color: [234, 179, 8]} // Yellow
    ].filter(s => s.val > -Infinity);
    
    strats.sort((a,b) => b.val - a.val);
    const winner = strats[0];
    const runnerUp = strats[1];
    const diff = winner.val - (runnerUp ? runnerUp.val : 0);
    const fmt = (n) => `£${Math.round(n).toLocaleString()}`;

    // ================= PAGE 1: EXECUTIVE SUMMARY =================
    addHeader("Strategic Wealth Report");
    
    // 1. The Verdict Banner
    doc.setFillColor(...winner.color);
    doc.roundedRect(margin, 30, width - (margin*2), 35, 3, 3, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("RECOMMENDED STRATEGY:", margin + 5, 40);
    
    doc.setFontSize(22);
    doc.text(winner.name.toUpperCase(), margin + 5, 52);
    
    doc.setFontSize(14);
    doc.text(`+ ${fmt(diff)} vs next best option`, width - margin - 5, 52, { align: 'right' });

    // 2. High Level Stats Grid
    let y = 75;
    doc.setTextColor(0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(`Projections after ${data.simYears} Years:`, margin, y);
    
    y += 10;
    const stats = [
        ['Net Worth', fmt(winner.val)],
        ['Liquid Cash', fmt(data.valuationMode === 'gross' ? r['strat'+(winner.name.includes('Rent')?'A':'B')].netWorthLiquid[idx] : winner.val)], // Approx
        ['Compared to Renting', fmt(winner.val - data.getNW(r.stratA, idx))]
    ];
    
    doc.autoTable({
        startY: y,
        head: [['Metric', 'Value']],
        body: stats,
        theme: 'striped',
        headStyles: { fillColor: [79, 70, 229] },
        margin: { left: margin, right: margin }
    });
    
    // 3. Narrative
    y = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(12);
    doc.text("Why this strategy wins:", margin, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    
    const narrativeLines = [
        `Based on your inputs, ${winner.name} outperforms others by generating higher total wealth.`,
        winner.type === 'Rent' 
            ? `By renting, you avoid significant ownership costs (Interest, Maintenance, Stamp Duty). The key driver is the investment return on your surplus cash.`
            : `Property ownership acts as a leveraged investment. The capital appreciation on the asset value (${data.i.personal.propertyGrowth}%) outweighs the mortgage interest costs.`,
        `Evaluation Mode: ${data.valuationMode === 'liquid' ? 'Liquid Cash (After selling costs & taxes)' : 'Gross Equity (Paper wealth)'}.`
    ];
    
    doc.text(narrativeLines, margin, y + 7, { maxWidth: width - (margin*2), lineHeightFactor: 1.5 });

    addFooter(1);

    // ================= PAGE 2: VISUAL ANALYSIS =================
    doc.addPage();
    addHeader("Visual Analysis");
    
    // Chart 1: Net Worth
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Wealth Timeline (${data.simYears} Years)`, margin, 35);
    
    const imgNW = getChartImage('netWorthChart');
    doc.addImage(imgNW, 'PNG', margin, 40, width - (margin*2), 80);
    
    // Chart 2: Dead Money
    doc.text(`Dead Money Analysis (Cumulative Costs)`, margin, 135);
    const imgDM = getChartImage('deadMoneyChart');
    doc.addImage(imgDM, 'PNG', margin, 140, width - (margin*2), 80);
    
    // Context
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Dead Money represents unrecoverable costs: Rent, Mortgage Interest, Maintenance, and Taxes. Minimizing this bar is often key to wealth accumulation.", margin, 230, { maxWidth: width - (margin*2) });

    addFooter(2);

    // ================= PAGE 3: ASSUMPTIONS =================
    doc.addPage();
    addHeader("Model Assumptions");
    
    // Personal Inputs
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Personal Profile", margin, 35);
    
    const p = data.i.personal;
    const personalData = [
        ['Current Rent', `£${p.rent.current}`],
        ['Liquid Cash', `£${p.liquidAssets}`],
        ['Monthly Savings', `£${p.monthlySavings}`],
        ['Tax Band', p.taxBand.charAt(0).toUpperCase() + p.taxBand.slice(1)],
        ['Stock Growth', `${p.stockGrowth}%`],
        ['Rent Inflation', `${p.rent.inflation}%`]
    ];
    
    doc.autoTable({
        startY: 40,
        head: [['Input', 'Value']],
        body: personalData,
        theme: 'plain',
        styles: { fontSize: 9 },
        margin: { left: margin, width: 80 }
    });
    
    // Property Inputs
    if (data.i.home.active) {
        const h = data.i.home;
        doc.text("Main Home Target", width/2 + 10, 35);
        const homeData = [
            ['Price', `£${h.price}`],
            ['Deposit', `${h.depositPct}%`],
            ['Rate', `${h.rate}% (${h.term}y)`],
            ['Growth', `${p.propertyGrowth}%`],
            ['Maintenance', `${h.repairRate}%`]
        ];
        
        doc.autoTable({
            startY: 40,
            head: [['Input', 'Value']],
            body: homeData,
            theme: 'plain',
            styles: { fontSize: 9 },
            margin: { left: width/2 + 10 }
        });
    }

    // Disclaimer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(100);
    const disclaimer = "This report is for educational purposes only and does not constitute financial advice. Projections are based on constant growth assumptions and current UK tax rules. Actual market conditions will vary.";
    doc.text(disclaimer, margin, height - 30, { maxWidth: width - (margin*2) });
    
    // QR Code / Link Placeholder
    doc.setTextColor(79, 70, 229);
    doc.setFont("helvetica", "bold");
    doc.textWithLink("Click here to open this scenario in your browser", margin, height - 20, { url: window.location.href });

    addFooter(3);
    
    doc.save(`Property_Strategy_${new Date().toISOString().split('T')[0]}.pdf`);
}
